name: all-regions
concurrency:
    group: export-${{ github.event.inputs.dest_repo }}-${{ github.event.inputs.dest_path || 'data/issues.json' }}
    cancel-in-progress: true
on:
  workflow_dispatch:
    inputs:
      labels:
        description: "Comma-separated labels (optional)"
        required: false
        default: ""
      source_repo:
        description: "Destination repo (owner/name)"
        required: true
        default: "https-multiculturaltoolbox-com/edge7"
      dest_branch:
        description: "Destination branch"
        required: false
        default: "main"
      dest_path:
        description: "Path in destination repo (e.g., data/issues.json)"
        required: false
        default: "data/issues.json"

      dateEnd:
        description: "Source owner (where big JSON lives)"
        required: false
        default: ""
      dateStart:
        description: "Source repo"
        required: false
        default: ""
      path:
        description: "Path to big JSON in source repo"
        required: true
        default: "cache/report:::VII"
      region:
        description: "Ref in source repo"
        required: false
        default: "VII"
      dest_repo:
        description: "Destination repo owner/name"
        required: true
        default: "pacuitinfo/edge43"
  schedule:
    - cron: '3 */6 * * 1-5'

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch export-issues per region
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}   # PAT w/ repo + workflow scopes recommended
          WORKFLOW_REPO: ${{ github.repository }}                   # repo that hosts export-issues.yml
          WORKFLOW_FILE: export-issues.yml
          BRANCH: ${{ github.event.inputs.dest_branch || 'main' }}
          REGIONKEY:  ${{ github.event.inputs.regionKey }}
          SOURCE_REPO: ${{ github.event.inputs.source_repo }}
          DEST_REPO:   ${{ github.event.inputs.dest_repo }}
          DEST_BRANCH: ${{ github.event.inputs.dest_branch || 'main' }}
          DEST_PATH:   ${{ github.event.inputs.dest_path }}
          LABELS:      ${{ github.event.inputs.labels || '' }}
          DATE_START: ${{ github.event.inputs.dateStart }}
          DATE_END: ${{ github.event.inputs.dateEnd }}
          REGION: ${{ github.event.inputs.region }}
        run: |
          set -euo pipefail
      
          if [ -z "${LABELS}" ]; then
            REGIONS=( "I" "II" "III" "IV-A" "IV-B" "V" "VI" "VII" "VIII" "IX" "X" "XII" "XIII" "XIV" )
          else
            IFS=',' read -r -a REGIONS <<< "${LABELS}"
          fi
          
          for region in "${REGIONS[@]}"; do
            gh workflow run "${WORKFLOW_FILE}" \
              -R "${WORKFLOW_REPO}" \
              -r "${BRANCH}" \
              -f source_repo="${SOURCE_REPO}" \
              -f region="${region}" \
              -f source_path="report_${region}.json" \
              -f dateStart="${DATE_START}" \
              -f dateEnd=" ${DATE_END}" \
              -f dest_repo="${DEST_REPO}" \
              -f dest_branch="${DEST_BRANCH}" \
              -f dest_path="report_${region}.json" \
              -f path="cache/report:${region}.json" \
              -f labels="${region}"
            echo "Dispatched for region: ${region}"
          done
      
